import React from "react";
import Head from "next/head";
import Link from 'next/link';

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto text-center mt-5">
          <h1 className="text-3xl text-purple-500">NEXT JS</h1>
          <Link href="/todos"><a><button className="mt-5 py-2 px-6 rounded-lg bg-blue-500 hover:bg-blue-400 text-white">Todos</button></a></Link>
          
      </main>
    </>
  );
}

export default Home;
