import axios from "axios";
import Head from "next/head";
import Link from "next/link";

function Todos({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto mt-10">
        <h1 className="text-center mb-7 text-xl font-bold">Todo Lists</h1>
        <div class="flex justify-center">
          <Link href="/"><a><button className="content-center py-2 px-4 bg-blue-500 mb-5 hover:bg-blue-400 text-white rounded-lg">Back Home</button></a></Link>
        </div>
        <ul>
          {data.map((todo) => {
            return (
              <Link key={todo.title} href="/todos/[id]" as={`/todos/${todo.id}`}>
                <a>
                  <li
                    className="border border-green-500 p-4 capitalize hover:bg-gray-200 mb-5 hover:shadow-md rounded-lg"
                  >
                    {todo?.title ?? ""}
                  </li>
                </a>
              </Link>
            );
          })}
        </ul>
      </main>
    </>
  );
}

Todos.getInitialProps = async () => {
//   try {
//     // const data = await fetch("https://jsonplaceholder.typicode.com/posts")
//     //   .then((response) => response.json())
//     //   .then((json) => {
//     //     return json;
//     //   });
//     const data = await axios.get("https://jsonplaceholder.typicode.com/posts")
//     .then((result) => {
//       return result.data;
//     })

//     return { data };

//   } catch (error) {
//     console.log(error);
//   }
// };

  // cara menggunakan instance axios
  try {
      const data = await axios.get('https://jsonplaceholder.typicode.com/posts');

      return {
        data: data.data
      }

  } catch(err) {
    
  }

}

export default Todos;
