import Head from "next/head";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

import courses from "../../constraints.js/api/courses";

import Footer from "../../parts/Footer";
import Header from "../../parts/Header";
import ListCourse from "../../parts/ListCourses";

function Courses({ data }) {
  // console.log(data.data);

  const [Search, setSearch] = useState("");
  const [SearchFocus, setSearchFocus] = useState(false);
  const [Courses, setCourses] = useState([]);
  const [Loading, setLoading] = useState(false);
  const [isError, setIsError] = useState(false);

  const inputWrapper = useRef(null);

  function handleClickOutside(e) {
    if (inputWrapper && !inputWrapper.current.contains(e.target)) {
      setSearch("");
    }
  }

  function handleSearch(e) {
    e.persist();
    setSearch(e.target.value);
    setLoading(true);

    setTimeout(() => {
      courses
        .all({ params: { q: e.target.value } })
        .then((result) => {
          setLoading(false);
          setCourses(result.data);
        })
        .catch((err) => {
          setLoading(false);
          setCourses([]);
          setIsError(true);
        });
    }, 1000);
  }

  useEffect(() => {
    window.addEventListener("mousedown", handleClickOutside);

    return () => {
      window.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section style={{ height: 360 }} className="relative overflow-hidden">
        <div className="absolute inset-0 z-0 w-full h-full bg-black opacity-75"></div>
        <div
          className="absolute z-0 bottom-0 w-full"
          style={{ marginBottom: "50px" }}
        >
          <h1
            className="text-6xl text-center font-semibold mb-5"
            style={{ color: "#36C2CF" }}
          >
            Library
          </h1>
          <p className="text-center text-white text-md">
            Jangan mau kalah update dengan yang lainnya. <br></br> Yuk iikuti
            pekerkembangan teknologi.
          </p>
        </div>

        <div className="container relative mx-auto z-20 pt-10">
          <Header onDark login></Header>
        </div>
      </section>

      <section
        ref={inputWrapper}
        className="relative w-full bottom-0 mx-auto text-center"
      >
        <div className="transform -translate-y-1/2">
          <input
            value={Search}
            onChange={handleSearch}
            onFocus={() => setSearchFocus(!SearchFocus)}
            onBlur={() => setSearchFocus(!SearchFocus)}
            type="text"
            className="border border-gray-400 px-4 py-2 w-3/4 md:w-1/4 bg-white z-10"
            placeholder={
              SearchFocus ? "Ketik minimal 3 karakter" : "Lagi nyari kelas apa?"
            }
          />
        </div>
        {Search.length >= 3 && (
          <div className="w-full -m-5 flex justify-center items-center mx-auto">
            <div className="w-3/4 md:w-1/4 bg-white border border-gray-400">
              {Loading ? (
                <div className="">Loading...</div>
              ) : (
                Courses.length > 0 ?
                Courses.map((item, index) => {
                  return (
                    <div
                      key={index}
                      className="px-2 py-2 hover:bg-gray-300 flex items-center"
                    >
                      <Link href={`/courses/[id]`} as={`/courses/${item.id}`}>
                        <a className="cursor-pointer flex">
                          <img width={80} src={item.thumbnail} alt="" />
                          <div className="text-left ml-5">
                            <h1 style={{ color: "#132B50" }}>{item.name}</h1>
                            <h1 className="text-sm text-gray-400 capitalize">
                              {item.level}
                            </h1>
                          </div>
                        </a>
                      </Link>
                    </div>
                  );
                }) : 'Item Not Found'
              )}
            </div>
          </div>
        )}
      </section>

      <section className="container mx-auto mt-20 mb-12">
        <ListCourse data={data.data}></ListCourse>
      </section>

      <section className="mt-24">
        <Footer></Footer>
      </section>
    </>
  );
}

Courses.getInitialProps = async () => {
  try {
    const data = await courses.all();

    return { data: data };
  } catch (err) {}
};

export default Courses;
